<CustButton@Button>
    text_size: self.text_size
    halign: 'left'
    valign: 'middle'
    color: 0, 0, 0, 0.8
    font_name: "assets/inter-font-family/Inter-Medium.ttf"
    background_down: 'assets/Grey.png'
    background_normal: ''

<AgainButton@ToggleButton>
    background_normal: "assets/srs-buttons/again-up.png"
    background_down: "assets/srs-buttons/again-down.png"
    border: (0, 0, 0, 0)
<HardButton@ToggleButton>
    background_normal: "assets/srs-buttons/hard-up.png"
    background_down: "assets/srs-buttons/hard-down.png"
    border: (0, 0, 0, 0)
<GoodButton@ToggleButton>
    background_normal: "assets/srs-buttons/good-up.png"
    background_down: "assets/srs-buttons/good-down.png"
    border: (0, 0, 0, 0)
<Tag@Button>
    background_normal: ''
    background_color: (0, 0, 0, 0)
    back_color: (1, 0, 0, 1)
    border_radius: [6]
    height: 23
    width: 60
    font_size: 10
    font_name: "assets/inter-font-family/Inter-Medium.ttf"
    canvas.before:
        Color:
            rgba: self.back_color
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: self.border_radius

<TaskLayout@Widget>:
    background_color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgba: root.background_color
        Rectangle:
            pos: self.pos
            size: self.size

<Task@FloatLayout>:
    id: task
    CustButton:
        text_size: self.text_size
        size: self.texture_size
        size_hint: 0.75, 0.078
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        Label:
            font_size: 18
            font_name: "assets/inter-font-family/Inter-Medium.ttf"
            text: "Thermodynamics Lab"
            halign: 'left'
            valign: 'top'
            color: 0, 0, 0, 0.9
            pos: self.parent.x+63, self.parent.y-4
        Tag:
            text: "CHEM 1220"
            pos: self.parent.x+24, self.parent.y+7
        AgainButton:
            size: 32, 32
            pos: self.parent.width*0.85, self.parent.y*1.050
        HardButton:
            size: 32, 32
            pos: self.parent.width*0.95, self.parent.y*1.050
        GoodButton:
            size: 32, 32
            pos: self.parent.width*1.05, self.parent.y*1.050
